# Generated by Django 4.1.5 on 2023-01-12 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12, verbose_name='Post Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('short_desc', models.CharField(max_length=30, verbose_name='description')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('image', models.ImageField(default='NONE', upload_to='images', verbose_name='Photo/Picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Feed.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('text', models.TextField(verbose_name='text')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's nickname")),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Feed.post', verbose_name='Post')),
            ],
        ),
    ]
