# Generated by Django 4.1.5 on 2023-01-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=12, verbose_name='Post Category')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Surname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('inban', models.BooleanField(default=False, verbose_name='Banned')),
                ('date', models.TimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('image', models.ImageField(default='NONE', upload_to='images', verbose_name='Photo/Picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Feed.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Feed.creator', verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Nickname')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('text', models.TextField(verbose_name='text')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Feed.post', verbose_name='Post')),
            ],
        ),
    ]
